adim: 384
aheads: 6
eunits: 1536
elayers: 8
transformer_input_layer: conv3d
dropout_rate: 0.1
transformer_attn_dropout_rate: 0.1
transformer_encoder_attn_layer_type: rel_mha
macaron_style: True
use_cnn_module: True
cnn_module_kernel: 31
zero_triu: False
a_upsample_ratio: 1
relu_type: swish
ddim: 384
dheads: 6
dunits: 1536
dlayers: 4
lsm_weight: 0.1
transformer_length_normalized_loss: False
mtlalpha: 0.1
ctc_type: builtin
rel_pos_type: latest
