defaults:
  - _self_
  - data: CCS_hand
  - model: default
  - optimizer: adamw
  - trainer: train
  - decode: default
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled
hydra:  
  output_subdir: null  
  run:  
    dir: .
exp_dir:
exp_name:
gpus: 1
slurm_job_id:
file_path: /home/guanjie/project/Cued-Agent/HS-0001.mp4
ckpt_path: /home/guanjie/project/Cued-Agent/ckpt/H_multi_lip.ckpt
pretrained_model_path:
transfer_frontend:
transfer_encoder:
num-nodes: 1

