defaults:
  - _self_
  - data: default
  - model: default
  - optimizer: adamw
  - trainer: train
  - decode: default
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled
hydra:  
  output_subdir: null  
  run:  
    dir: .
exp_dir: results
exp_name: test_run_pretrained
gpus: 0
slurm_job_id: null
file_path:
ckpt_path: null
pretrained_model_path: pretrained_vsr/LRS3_V_WER19.1/model.pth
transfer_frontend: True
transfer_encoder:

